### ISSUE TITLE
Feature request: glyrc working without -a option

### ISSUE THREAD

**Issue by cassiel74** [sahib/glyr#62]
It would be nice for glyrc to work without -a option or other similar solution.

I wrote a simple shell script to fetch lyrics for cmus, it takes artist/title arguments from `cmus-remote -Q` but what if you are listening a cover? 
Eg, for "Crossroads guitar festival 2013", the artist tag reported from `cmus-remote -Q` is 
`tag artist Gregg Allman, Warren Haynes & Derek Trucks`
so
`glyrc lyrics -a "Gregg Allman, Warren Haynes & Derek Trucks" -t "the needle and the damage done"` fails.

**Comment by sahib** [comment]
Hi,

I don't think this is in the scope of glyr. Most sites need an artist to search for. In order to "autodetect" it, I would need to lookup the title on (e.g.) musicbrainz to get a suitable artist (or get the original artist of the cover). 

The possible cases are just too many too handle for libglyr itself. If you know that you have such cases, you can implement such special cases for yourself.

**Comment by cassiel74** [comment]
Just for clarity, I am not interested in getting the original artist but just the lyrics.
Anyway, I got it working with an empty "-a" 
`glyrc lyrics -a "" -t "the needle and the damage done"`

**Comment by sahib** [comment]
Sure, but to search on most sites glyr needs the correct artist to search for.
The empty artist is indeed a (slightly weird) workaround for this. Forgot to mention, sorry. 

So, closing.
