### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by rnixx** [sahib/glyr#82]
Hi,

would you be willing to license this lib including the python bindings under LGPL?

**Comment by sahib** [comment]
Hello,

may I ask what your usecase for ``glyr`` would be?

**Comment by rnixx** [comment]
Displaying cover arts in an audio player. But this player is part of a bigger non FOSS project so GPL prevents me using it.

My general attitude with the GPL is that it's good for entire applications, but I'm convinced that libraries benefit in the end from more liberal licensing

**Comment by sahib** [comment]
My mindset also has changed a bit regarding this, so I'd be happy to relicense ``libglyr`` and ``python-glyr`` as LGPL. My hope is that it will attract more developers that maintain glyr, since I can't really bring up the time anymore to do that.

I might take a few days until I have the time to exchange the license files in the source.

**Comment by rnixx** [comment]
OK, then one more question. I don't know HOW liberal you want to go, there's also other other options like MIT, Apache, BSD, etc.

If you tell me which license you want to go I can alter the licensing information and make a PR.

Thanks

**Comment by sahib** [comment]
Yes, I'm aware of these licenses but I still like the idea behind the GPL.
The new license would be [LGPLv3](https://www.gnu.org/licenses/lgpl-3.0.html).

I'm going to exchange the license myself later the day, but thanks for the offer of a PR.

**Comment by rnixx** [comment]
OK, Thank you!
